baseURL: "https://congchan.github.io/"
title: Fly me to the Moon
paginate: 10
theme: PaperMod
defaultContentLanguage: en-us

permalinks:
    posts: /archives/:slug/

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: G-JEPTGNZ7TJ

minify:
    disableXML: true
    minifyOutput: false

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    #title: iblog.zone
    description: "Hi, this is Cong. I’m documenting my learning notes in this blog."
    author: Cong
    # author: ["Me", "You"] # multiple authors
    #images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "2006-01-02"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowAllPagesInArchive: true
    ShowReadingTime: true
    ShowShareButtons: true
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowFullTextinRSS: true
    ShowToc: true
    tocopen: false  # 让TOC显示但自动收起
    comments: true
    mainSections:
        - posts


    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/favicons/favicon.ico"
        favicon16x16: "/favicons/favicon-16x16.png"
        favicon32x32: "/favicons/favicon-32x32.png"
        apple_touch_icon: "/favicons/apple-touch-icon.png"
        safari_pinned_tab: "<link / abs url>"

    #label:
    #    text: "iblog.zone"
    #    icon: 
    #    iconHeight: 35

    editPost:
        URL: "https://github.com/<gitlab user>/<repo name>/tree/<branch name>/<path to content>/"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # profile-mode
    #profileMode:
    #    enabled: false # needs to be explicitly set
    #    title: ExampleSite
    #    subtitle: "This is subtitle"
    #    imageUrl: "<img location>"
    #    imageWidth: 120
    #    imageHeight: 120
    #    imageTitle: my image
    #    buttons:
    #        - name: Posts
    #          url: posts
    #        - name: Tags
    #          url: tags

    # home-info mode
    homeInfoParams:
        Title: "Welcome to Cong's Log"
        Content: >
            Hi, this is Cong. I’m documenting my learning notes in this blog.

    socialIcons:
        - name: github
          url: "https://github.com/congchan"
        - name: Rss
          url: "index.xml"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: 5
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 10
        - identifier: search
          name: Search
          url: /search/
          weight: 30
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        
# for search
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
